### ISSUE TITLE
One liner double_t fix

### ISSUE THREAD

**Issue by Unitrunker** [anthonix/ffts#82]
This commit ...

https://github.com/anthonix/ffts/commit/92c8a59dfedf9c920520871e8e6b2d41ef11d02a

Missed one line:

https://github.com/anthonix/ffts/blob/fe86885ecafd0d16eb122f3212403d1d5a86e24e/src/ffts_trig.c#L884

Missing "ffts_" prefix on that line. FYI - compiles fine on VS.2017 with defines:

HAVE_STDINT_H
HAVE_STDLIB_H
HAVE_STRING_H

**Comment by Unitrunker** [comment]
I see linkotec's branch is more up to date.

**Comment by RoyiAvital** [comment]
Where is the *more updated* branch?
